// <auto-generated />
namespace ProjectExamenCSHARP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class creation_base_de_donnee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creation_base_de_donnee));
        
        string IMigrationMetadata.Id
        {
            get { return "202503081558226_creation_base_de_donnee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
